
name: Conventional commit check

on: [ push, pull_request ]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Conventional commit check
        uses: oknozor/cocogitto-action@v1
        with:
          git-user: 'github-actions'
          git-user-email: 'github-actions@github.com'